wallpaper {
	monitor = DP-3
	path = ~/Documents/Wallpapers/carina.png
}

wallpaper {
	monitor = DP-2
	path = ~/Documents/Wallpapers/MountainSkyline.png
}

wallpaper {
	monitor = DP-1
	path = ~/Documents/Wallpapers/MountainSkyline.png
}

wallpaper {
	monitor = HDMI-A-1
	path = ~/Documents/Wallpapers/MountainSkyline.png
}

splash = false
